### ISSUE TITLE
ABORTED state of move_base action

### ISSUE THREAD

**Issue by yutakaoka** [at-wat/neonavigation#114]
Hi,

Do you have any plan to consider "ABORTED" state of move_base action?
For example, when the planner tries recovery motion sometimes, but if it fails, move_base action might publish "ABORTED".
Any thoughts?

Thanks,
Yutaka

**Comment by at-wat** [comment]
This sounds good to be added.

I might not be able to do it very soon.
Pull-Request is always welcome and appreciated.

**Comment by at-wat** [comment]
Thank you for your effort!
