### ISSUE TITLE
Trajectory Tracker & Path Following

### ISSUE THREAD

**Issue by timurlautan** [at-wat/neonavigation#214]
Exusme.. help me please, how to run trajectory tracker node and path following node.. and can i u make virtual corridor.. thanks

**Comment by at-wat** [comment]
see the sample launch files at https://github.com/at-wat/neonavigation/tree/master/neonavigation_launch/launch

**Comment by at-wat** [comment]
Please reopen the issue or create a new issue if more information is required.
Having more concrete requirement how do you want to use it would be helpful for me to explain how.
