### ISSUE TITLE
trajectory_tracker: unused parameters exist

### ISSUE THREAD

**Issue by ykoga-kyutech** [at-wat/neonavigation#273]
I found that unused parameters exist in trajectory_tracker node.

- `distance_angle_factor`
https://github.com/at-wat/neonavigation/search?q=ang_factor_&unscoped_q=ang_factor_

- `switchback_dist`
https://github.com/at-wat/neonavigation/search?q=sw_dist_&unscoped_q=sw_dist_

- `k_dcel`
https://github.com/at-wat/neonavigation/search?q=dec_&unscoped_q=dec_

Those parameters should be used in this node or deleted.

**Comment by at-wat** [comment]
All of them look been unused since the end of 2014.
I think they are fine to be simply removed.

**Comment by ykoga-kyutech** [comment]
OK, I'll send a PR soon.
