### ISSUE TITLE
Error: Given goal is not on the map 

### ISSUE THREAD

**Issue by HappySamuel** [at-wat/neonavigation#325]
Hi

I tried to use mcl_3dl together with the neonavigation in Gazebo simulation. 

![Screenshot from 2019-06-14 12-14-49](https://user-images.githubusercontent.com/18137963/59483041-1f24e780-8e9e-11e9-8eed-b3632a2c29f7.png)

However, when i tried to send a goal on the map in RVIZ, the error appear as below:

![Screenshot from 2019-06-14 12-07-51](https://user-images.githubusercontent.com/18137963/59483062-34017b00-8e9e-11e9-8af8-e27bcb49e987.png)

And i refer back to running demo.launch. I found that the goal sent via RVIZ is 0 elevation in z-axis. Please advise how should i send a goal without elevation in z-axis. 
Thanks.

Best,
Samuel

**Comment by at-wat** [comment]
Z position is simply ignored in planner_3d node.
Third value shown in `New goal received` INFO message is yaw orientation.

I guess you are sending a goal on non-map frame. (related to a bug #324 )
Please try setting `Global Options`/`Fixed Frame` of rviz to map.

**Comment by HappySamuel** [comment]
Hi @at-wat 

I checked my RVIZ configuration again and found that i am having the setting as you said Global Options / Fixed Frame with map. But the problem still the same. What shall i do next?

Best,
Samuel

**Comment by HappySamuel** [comment]
Hi @at-wat 

Another discover, i tested your neonavigation demo with my map (pgm or png), but the error is the same. "Given goal is not on the map". So i guess the problem lies with the map? My map size is 2048x2048. Please advise what shall i do now? 
Thank you.

Best,
Samuel

**Comment by at-wat** [comment]
@HappySamuel could you attach map yaml file (or header part of `rostopic echo /map`) and `rostopic echo /move_base_simple/goal`?

**Comment by HappySamuel** [comment]
Hi @at-wat 

I found that if i use a map that is created by 2D lidar. It can works well. Do you know any tools that i can use for creating the 2D map from 3D lidar pointcloud or pcd map?

Best,
Samuel

**Comment by at-wat** [comment]
@HappySamuel please attach example data which doesn't work well.
Map yaml file, header part of `rostopic echo /map`, and result of `rostopic echo /move_base_simple/goal` might help.

**Comment by at-wat** [comment]
> Do you know any tools that i can use for creating the 2D map from 3D lidar pointcloud or pcd map?

@HappySamuel I used to use `pointcloud_to_maps` node in neonavigation/map_organizer package. (https://github.com/at-wat/neonavigation/tree/master/map_organizer#pointcloud_to_maps)
But, it is not well maintained at now and I'm not sure it works well.

**Comment by HappySamuel** [comment]
Hi @at-wat 

I accidentally deleted the failed map. Then I tried to reproduce the same error. But i couldn't. It's weird. I use the same procedure that i created map last time, which result the above issue. But the map i produced. there is no error. I am sorry that i couldn't provide you the information you need.

Best,
Samuel

**Comment by HappySamuel** [comment]
Hi @at-wat 

I found the cause of the error as described from beginning. It's caused by the 3rd element of origin as non-zero value

> origin: [65.20000, -59.40000, 1.5707963]

![Screenshot from 2019-11-21 16-41-22](https://user-images.githubusercontent.com/18137963/69321290-c3952c00-0c7d-11ea-8733-26ff58525e41.png)

But when i changed the 3rd element of origin to zero as shown as below:

![Screenshot from 2019-11-21 16-40-47](https://user-images.githubusercontent.com/18137963/69321253-b5dfa680-0c7d-11ea-9dde-a3c90d52537b.png)

Only then the move_base can receive the goal.

But when i tried to change the 3rd element of origin to 0.1, the result become as below.

![Screenshot from 2019-11-21 16-54-48](https://user-images.githubusercontent.com/18137963/69322364-ad886b00-0c7f-11ea-9bff-00890a5a0fd8.png)

Do you know why?

Best,
Samuel

**Comment by at-wat** [comment]
> 3rd element of origin

@HappySamuel Currently, costmap_cspace package doesn't handle the 3rd element of origin (yaw orientation), but rviz looks do.
costmap_2d and amcl in navigation stack seems also ignoring orientation.

**Comment by HappySamuel** [comment]
Hi @at-wat 

Is that means the 2D map i created must be having the same origin (X,Y,yaw) as 3D map i used?

Best,
Samuel

**Comment by at-wat** [comment]
Yes, coordinate frame of localization and navigation must be matched.
x, y can be adjusted by using 2D map origin in yaml, but orientation should be aligned beforehand.

**Comment by at-wat** [comment]
#401 will track the rotation component support for OccupancyGrid origin.
Feel free to add comments to there and/or creating PRs.
