### ISSUE TITLE
Asking for permission for uploading video

### ISSUE THREAD

**Issue by HappySamuel** [at-wat/neonavigation#328]
Hi

I wish to upload my recent result on using your neonavigation on Gazebo simualtion. Can i upload the video to youtube, since i am implementing neonavigation? It's good to use. Thank you very much.

Best,
Samuel

**Comment by at-wat** [comment]
I welcome uploading such kind of video.
Including a link to the repository would be great.

BTW, latest release version of the planner has a bug which makes planned path nonsmooth. 
Using master branch might get better result.

**Comment by HappySamuel** [comment]
Hi @at-wat 

Sure, i will definitely include a link to this repository. For your info, i am currently using the master branch.

Best,
Samuel
