### ISSUE TITLE
Footprint and Pathvelocity don't show up on RVIZ - TF error

### ISSUE THREAD

**Issue by HappySamuel** [at-wat/neonavigation#331]
Hi

I change the dummy robot to my own robot model, but i couldn't have footprint and pathvelocity to be visualized on the RVIZ. Whenever i use the dummy robot, these two are shown properly. The error shows that is due to the TF error. The picture below showed the error message on RVIZ:
![Screenshot from 2019-06-21 11-20-21](https://user-images.githubusercontent.com/18137963/59895285-97e3f080-9416-11e9-91a7-4972ef8a5fd6.png)

Here's the launch file:
![Screenshot from 2019-06-21 11-21-21](https://user-images.githubusercontent.com/18137963/59895427-28223580-9417-11e9-9ac1-e81c325531dd.png)

Here's the tf tree:
![frames](https://user-images.githubusercontent.com/18137963/59895471-5273f300-9417-11e9-90ae-f1d1f4991538.png)

Please advise what should i do to have them to be visualized on RVIZ. Thank you very much.

Best,
Samuel

**Comment by at-wat** [comment]
It looks like not a neonavigation problem but a general simulation time configuration problem.
The error from rviz said that the data you want to show has a timestamp of current wall time, but the latest transform timestamp points 50 years ago, or 169 seconds after Unix time epoch.
I guess `use_sim_time` setting is incorrect.

**Comment by HappySamuel** [comment]
Hi @at-wat 

Thank you for helping, this error is indeed raised due to ``` use_sim_time ``` setting is incorrect. I manage to get rid of this error.

Best,
Samuel
