### ISSUE TITLE
Does safety_limiter do the velocity smoothening with acceleration limit given?

### ISSUE THREAD

**Issue by HappySamuel** [at-wat/neonavigation#386]
Hi

Recently, i tested with the trajectory_tracker with following a pre-recorded path (with velocity). Together with the trajectory_tracker's output, i multiplexes with others' output. If i stop the AGV with others' output, while the trajectory_tracker's output being hold back (linear.x > 1m/s). When i release the stopping command, the AGV will then shoot out. Is there a way to smooth the accelerating process? 

Can the safety_limiter being used for smoothing accelerating? Or any suggestion open source will do this?

Best,
Samuel

**Comment by at-wat** [comment]
@HappySamuel `safety_limiter` doesn't have smoothing.
As smoothing (= LPF) has delay, it can easily let position control system unstable.
Smoothing function should be carefully selected according to the type of higher/lower layer system.

I don't know the open-source node to smooth the velocity, but it should be very easy to implement.
In my case, low layer vehicle device driver has acceleration limit parameter.

**Comment by HappySamuel** [comment]
Hi @at-wat 

Thanks for the explanation. I found an open source that does this, it's called **yocs_velocity_smoother** that do this. 
By the way, can share which low layer vehicle device driver that you are using? So that i can look into that kind of device driver.

Best,
Samuel

**Comment by at-wat** [comment]
> low layer vehicle device driver

Sorry for delayed reply.
I often use http://t-frog.com/products/motor_driver/ this controller which works wth https://github.com/openspur/yp-spur and https://github.com/openspur/ypspur_ros.

**Comment by at-wat** [comment]
Closing as the question has been resolved.
Feel free to reopen or open a new issue if you have any related question.

**Comment by HappySamuel** [comment]
Sorry for forgetting to close it down. Thanks for your guidance.
