### ISSUE TITLE
Behavior discussion of the vehicle being hijacked to the middle of a pre-recorded path

### ISSUE THREAD

**Issue by HappySamuel** [at-wat/neonavigation#387]
Hi

 **Hijack** = seize the vehicle in transit, and force it to go to a different location
The common things between 2 scenarios:
First, send a pre-recorded path to the trajectory_tracker. 
Second, hijack the vehicle to the middle of the pre-recorded path.

Scenario 1:
(1) Manually drive the vehicle to the middle of the path
(2) Load pre-recorded path to trajectory_tracker
Result: The vehicle will directly start tracking the path from the middle of path till the end of path.

Scenario 2:
(1) Load pre-recorded path to trajectory_tracker
(2) Hijacked the vehicle when it is navigated by trajectory_tracker to the middle of path (do not stay on the path when hijacking, then put it back to the middle of path).
Result: The vehicle will not tracking the path but stay. Visualize of tracking marker is stay on the starting place that the vehicle being hijacked. 

Why does the trajectory_tracker behave differently for above 2 scenarios? Isn't the trajectory_tracker suppose to automatically relocate itself onto the given path and update its tracking marker to be in front of the AGV on that path?

Best,
Samuel

**Comment by at-wat** [comment]
To avoid tracking prior or posterior path strip close to the currently tracking position (for example at crossing point of the path), robot position on the path is incrementally updated except the first control step after receiving a new path.
If you want to restart tracking from middle of the path, please publish the path again.

**Comment by HappySamuel** [comment]
HI @at-wat 

Thank you for the guidance, i will do accordingly.

Best,
Samuel
