### ISSUE TITLE
Question of product-to-sum

### ISSUE THREAD

**Issue by liubing** [at-wat/neonavigation#468]
In planner_3d.cpp, line 1778:

`const bool dir = (cosf(yaw) * cosf(vel_yaw) + sinf(yaw) * sinf(vel_yaw) < 0);`

Why not write it like:

`const bool dir = (cosf(yaw - vel_yaw) < 0);`

I think they are mathematically equivalent, and the latter is simpler and cheaper to compute.

**Comment by at-wat** [comment]
Simplified one looks fine.
This line is executed for each generated path node (not in path searching), it's not very cost consuming.
