### ISSUE TITLE
Two sensor inputs for map_overlay

### ISSUE THREAD

**Issue by yutakaoka** [at-wat/neonavigation#77]
Hi,

Is there any way to deal with two sensor inputs(e.g laser and pointcloud) for making a "map_overlay" at once? I just wanted to utilize laser and point cloud info as one obstacle map.

Thanks,

**Comment by at-wat** [comment]
It is not yet supported by the nodes in the costmap_cspace package.
The simplest workaround is using `laser_filters scan_to_cloud_filter_chain` without any filter plugin to convert LaserScan to PointCloud2.
`pointcloud2_to_map` node supports multiple sources of the input cloud on one `cloud` topic.

**Comment by yutakaoka** [comment]
Thank you for your advice. It seemed to be working well.

**Comment by at-wat** [comment]
https://github.com/at-wat/neonavigation/pull/106 added the feature to overlay multiple costmaps.
